### ISSUE TITLE
Error on rspec test for #each

### ISSUE THREAD

**Issue by tuckyeah** [ga-wdi-boston/ruby-fibonacci-challenge#10]
I've been able to get my code to pass all the tests for FibonacciRange, except for the one for the #each method, which says it checks for "stores minimal state"

This is the error I get
[RSPEC]

```
1) FibonacciRange #each stores minimal state
     Failure/Error: require 'binding_of_caller'

     LoadError:
       cannot load such file -- binding_of_caller
     # ./spec/challenge_spec.rb:20:in `block (3 levels) in <top (required)>''
```

I checked with Chris and we compared it against the solution, but it still didn't seem to pass.

This is what my code looks like:

```
def each
    previous_fib = start
    current_fib = 1

    while previous_fib <= stop
      yield previous_fib
      next_fib = previous_fib + current_fib
      previous_fib = current_fib
      current_fib = next_fib
    end
  end
```

**Comment by jrhorn424** [comment]
Addressed as of https://github.com/ga-wdi-boston/ruby-fibonacci-challenge/commit/488a5ade57fb672f63fb3abb78131d40b7467549.

Thanks @tuckyeah!
