### ISSUE TITLE
Conflict in challenge_spec.rb

### ISSUE THREAD

**Issue by MFBrewster** [ga-wdi-boston/ruby-fibonacci-challenge#2]
in ./spec/challenge_spec.rb

lines 3-4 say: 
```ruby 
describe 'FibonacciRange' do 
subject(:fibonacci_range) { FibonacciRange.new(10) }
``` 

While the spec for the correct array asks for: ```[0, 1, 1, 2, 3, 5, 8]```

... which is the array for a stop value of '7', not '10'. I changed the stop value in line 4 to '7', and the spec worked fine.

Thank you!

**Comment by jrhorn424** [comment]
This is working as intended. Thanks @MFBrewster!
